<a href="https://colab.research.google.com/github/VANISAIDEEPIKA/5H2DEEPIKA/blob/main/assignments/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
# prompt: Import the numpy package under the name np

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [29]:
Y = np.zeros(10)
print(Y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [32]:
Y.size * Y.itemsize


80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [33]:

import numpy as np
help(np.add)
np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [36]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [37]:
import numpy as np
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [39]:
Z= np.arange(50)
Z = Z[::-1]
print(Z)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [41]:
import numpy as np
X = np.arange(9).reshape(3, 3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [42]:
import numpy as np
y = np.array([1,2,0,0,4,0])
ny = np.nonzero(y)
print(ny)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [43]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [44]:
b=np.random.random((3,3,3))
print(b)

[[[0.56627354 0.90418405 0.69506932]
  [0.00349383 0.07749932 0.98609049]
  [0.13554126 0.82742836 0.76287807]]

 [[0.9764444  0.65897546 0.49787039]
  [0.93738936 0.08409163 0.93140185]
  [0.87218435 0.1995799  0.67539058]]

 [[0.85273811 0.32051044 0.77116875]
  [0.60582297 0.04605075 0.28942558]
  [0.58179519 0.08857299 0.65220674]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [45]:
x=np.random.random((10,10))
print(x)
print(x.min())
print(x.max())

[[0.56761044 0.20224726 0.35588102 0.4804349  0.75671989 0.91700677
  0.86131883 0.24147828 0.03527965 0.28558869]
 [0.79700961 0.61753368 0.85577262 0.75967819 0.78642274 0.13355938
  0.62748533 0.15061775 0.19072001 0.17381453]
 [0.0267887  0.05878392 0.51110222 0.86165671 0.08787971 0.37676948
  0.95316229 0.15784118 0.64796475 0.85161174]
 [0.63555539 0.07674436 0.36071733 0.33793136 0.46054879 0.4767778
  0.43850024 0.62187783 0.25835223 0.04991352]
 [0.36269403 0.89279146 0.42377148 0.24041919 0.92431192 0.89208535
  0.52521201 0.65461939 0.61586898 0.02048247]
 [0.97806428 0.16375971 0.52175381 0.89226897 0.6514739  0.6576005
  0.19351084 0.89914825 0.31136406 0.63563086]
 [0.29312071 0.1330825  0.78495571 0.78318628 0.28331753 0.72778702
  0.553034   0.64300064 0.52461229 0.65126477]
 [0.25908771 0.74313163 0.35083772 0.32455727 0.31816812 0.46796498
  0.3146316  0.14921832 0.55532533 0.37896721]
 [0.48966447 0.85122643 0.87981284 0.29442809 0.40207453 0.79677481
  0.93811895 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [47]:
a=np.random.random(30)
b=a.mean()
print(b)

0.5240757738783253


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [48]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [49]:
y=np.random.random((10,10))
y=np.pad(y,pad_width=1,mode='constant',constant_values=0)
print(y)
y=np.random.random((10,10))
y[:,[0,-1]]=0
y[[0,-1],:]=0
print(y)

[[0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.47250942 0.18559549 0.2729416  0.83838445 0.50463493
  0.2035609  0.0104718  0.42449719 0.60918071 0.19140911 0.        ]
 [0.         0.99551729 0.01544286 0.79859138 0.39194536 0.33459196
  0.40143497 0.02741694 0.06240285 0.15824107 0.81665033 0.        ]
 [0.         0.80803609 0.84233874 0.52284533 0.3605926  0.41061412
  0.97382653 0.64658242 0.39818607 0.71093057 0.4108087  0.        ]
 [0.         0.56054313 0.34409962 0.22322011 0.72194116 0.91805079
  0.0864982  0.1964248  0.27787833 0.75891913 0.45698099 0.        ]
 [0.         0.19514063 0.37517614 0.78004842 0.90698032 0.58644839
  0.11524693 0.37762371 0.64416282 0.33045631 0.05808754 0.        ]
 [0.         0.17362517 0.12250038 0.16359139 0.90789665 0.23276157
  0.34972901 0.26582817 0.73429744 0.49680691 0.53893805 0.        ]
 [0.         0.57299382 0.50719133 0.77808396 0.0

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [50]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))

nan
False
False
nan
True


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [51]:
c= np.random.random((5,5))
print(c)
for i in range(1,5):
  c[i,i-1]=i
print(c)

[[0.49655408 0.76456535 0.89551086 0.959849   0.47095962]
 [0.92143167 0.75537245 0.47217002 0.21118528 0.58352792]
 [0.31392839 0.39732679 0.23679064 0.0590061  0.38682459]
 [0.47472779 0.6139094  0.83250146 0.63666994 0.14809659]
 [0.74485215 0.73182306 0.7315848  0.34918372 0.76283017]]
[[0.49655408 0.76456535 0.89551086 0.959849   0.47095962]
 [1.         0.75537245 0.47217002 0.21118528 0.58352792]
 [0.31392839 2.         0.23679064 0.0590061  0.38682459]
 [0.47472779 0.6139094  3.         0.63666994 0.14809659]
 [0.74485215 0.73182306 0.7315848  4.         0.76283017]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [52]:
b= np.random.random((8,8))
print(b)
for i in range(0,8):
  for j in range(0,8):
    if (i+j)%2==0:
      b[i,j]=0
print(b)

[[0.43444557 0.58126729 0.87255998 0.37898301 0.78175156 0.4097156
  0.57553196 0.1986337 ]
 [0.45846926 0.46227434 0.56388567 0.36478222 0.41357788 0.54468982
  0.86469702 0.40750431]
 [0.03824512 0.23725771 0.35955073 0.2171352  0.11843202 0.23030682
  0.06255107 0.2398286 ]
 [0.79246498 0.20455486 0.9592631  0.29478843 0.35679511 0.59848287
  0.39848819 0.62009364]
 [0.99496798 0.14659325 0.00243482 0.05215372 0.56034683 0.11772247
  0.69192446 0.17592241]
 [0.94525854 0.84667395 0.47582758 0.2549848  0.14561804 0.49817772
  0.57750826 0.42603099]
 [0.21127487 0.14031348 0.42965456 0.6437594  0.06805604 0.79636118
  0.60357593 0.94216901]
 [0.72855928 0.22764319 0.47413512 0.65852661 0.27255177 0.41990724
  0.43283789 0.81204715]]
[[0.         0.58126729 0.         0.37898301 0.         0.4097156
  0.         0.1986337 ]
 [0.45846926 0.         0.56388567 0.         0.41357788 0.
  0.86469702 0.        ]
 [0.         0.23725771 0.         0.2171352  0.         0.23030682
  0.       

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:
def find_index(element_number, shape):
  x = element_number // (shape[1] * shape[2])
  y = (element_number % (shape[1] * shape[2])) // shape[2]
  z = element_number % shape[2]
  return x, y, z

index_100 = find_index(99, (6,7,8))
index_100

(1, 5, 3)

In [25]:
np.random.random((6,7,8))

array([[[0.5253106 , 0.63313999, 0.3090423 , 0.70227058, 0.08423993,
         0.535581  , 0.64921461, 0.55066345],
        [0.19477836, 0.03700027, 0.3747581 , 0.00892922, 0.59189047,
         0.90551561, 0.89663734, 0.23716972],
        [0.15952417, 0.40311324, 0.51347379, 0.60688144, 0.93442126,
         0.99742248, 0.86410551, 0.19895523],
        [0.8630657 , 0.51553915, 0.14403538, 0.22145833, 0.50632027,
         0.359826  , 0.60447477, 0.74549337],
        [0.02017028, 0.94120244, 0.19413193, 0.62785634, 0.80895636,
         0.63343342, 0.13736297, 0.08297623],
        [0.84920846, 0.82204239, 0.59607364, 0.84073057, 0.97624947,
         0.18655151, 0.86041589, 0.66782302],
        [0.61696994, 0.66120518, 0.71423853, 0.44234386, 0.92510833,
         0.31688528, 0.41838757, 0.44254669]],

       [[0.0631892 , 0.72338929, 0.01409395, 0.35137652, 0.8331461 ,
         0.56400457, 0.02560444, 0.90621935],
        [0.00642507, 0.9585845 , 0.91773341, 0.26923821, 0.01778221,
         

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)