<a href="https://colab.research.google.com/github/VANISAIDEEPIKA/5H2DEEPIKA/blob/main/assignments/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [24]:
# prompt: Import the numpy package under the name np

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [25]:
print(np.__version__)
np.show_config()


1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [26]:
Y = np.zeros(10)
print(Y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [27]:
Y.size * Y.itemsize


80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [28]:

import numpy as np
help(np.add)
np.info(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [29]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [30]:
import numpy as np
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [31]:
Z= np.arange(50)
Z = Z[::-1]
print(Z)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [32]:
import numpy as np
X = np.arange(9).reshape(3, 3)
print(X)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [33]:
import numpy as np
y = np.array([1,2,0,0,4,0])
ny = np.nonzero(y)
print(ny)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [34]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [35]:
b=np.random.random((3,3,3))
print(b)

[[[0.08910962 0.29220134 0.05819197]
  [0.20494096 0.74675746 0.79124337]
  [0.83691973 0.06799157 0.0815143 ]]

 [[0.83444199 0.81681711 0.63961452]
  [0.76243984 0.2929209  0.3908099 ]
  [0.92418965 0.92998277 0.53331595]]

 [[0.67176561 0.95763964 0.65608198]
  [0.13240326 0.17698545 0.51980623]
  [0.97212757 0.02064482 0.43358712]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [36]:
X = np.random.random((10,10))
Xmin, Xmax = X.min(), X.max()
print(Xmin, Xmax)

0.029141068065109188 0.9855100728086502


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [37]:
a=np.random.random(30)
b=a.mean()
print(b)

0.5299519284739825


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [38]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [39]:
C = np.ones((5,5))
C = np.pad(C, pad_width=1, mode='constant', constant_values=0)
print(C)
# Using fancy indexing
C[:, [0, -1]] = 0
C[[0, -1], :] = 0
print(C)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [40]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
import numpy as np

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [42]:
A= np.zeros((8,8),dtype=int)
A[1::2,::2] = 1
A[::2,1::2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [43]:
def find_index(element_number, shape):
  x = element_number // (shape[1] * shape[2])
  y = (element_number % (shape[1] * shape[2])) // shape[2]
  z = element_number % shape[2]
  return x, y, z

index_100 = find_index(99, (6,7,8))
index_100 = np.unravel_index(99, (6,7,8))
print(index_100)

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [44]:
c = np.array([[0,1], [1,0]])
Z = np.tile(c,(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [45]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.25764615  0.73430596  0.99220945 -0.61431142  0.78820284]
 [-1.45242423  0.49829568  1.32903165 -1.20250905  0.07802248]
 [ 0.7361679  -0.66302162  0.61714645 -0.39665049 -1.48096174]
 [-1.02024714 -1.43793143 -0.43202383 -0.63475519 -0.42169141]
 [ 1.68360195 -0.08633691  1.66039629  1.27923906  0.7038909 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [46]:
color_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])
colors = np.array([
    (255, 0, 0, 255),   # Red
    (0, 255, 0, 255)    # Green
], dtype=color_dtype)
print("First color red channel:", colors[0]['red'])
print("Second color green channel:", colors[1]['green'])


First color red channel: 255
Second color green channel: 255


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [47]:
import numpy as np
b = np.dot(np.ones((5,3)), np.ones((3,2)))
print(b)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [48]:
x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [49]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [50]:
import numpy as np
Z = np.array([1, 2, 3, 4, 5], dtype=int)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# The original line caused the error. To fix it, you can use np.logical_and to combine two boolean arrays
print(np.logical_and(Z < Z, Z > Z)) # This would result in all False since no element can be simultaneously less than and greater than itself

[   1    4   27  256 3125]
[ 1  2  4  8 16]
[False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[1. 2. 3. 4. 5.]
[False False False False False]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [51]:
import numpy as np

# 1. np.array(0) / np.array(0)
result_1 = np.array(0) / np.array(0)
print("Result of np.array(0) / np.array(0):", result_1)

# 2. np.array(0) // np.array(0)
result_2 = np.array(0) // np.array(0)
print("Result of np.array(0) // np.array(0):", result_2)

# 3. np.array([np.nan]).astype(int).astype(float)
result_3 = np.array([np.nan]).astype(int).astype(float)
print("Result of np.array([np.nan]).astype(int).astype(float):", result_3)


Result of np.array(0) / np.array(0): nan
Result of np.array(0) // np.array(0): 0
Result of np.array([np.nan]).astype(int).astype(float): [-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆)

In [52]:
a = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(a)), a))

[-3.  1. -8. -5.  2. -8. -7. -3. -4.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [53]:
b = np.random.randint(0,10,10)
c = np.random.randint(0,10,10)
print(np.intersect1d(b,c))

[2 3 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [54]:
import numpy as np

# Ignore all warnings
np.seterr(all='ignore')

# Example of suppressed warnings
print(np.array(0) / np.array(0))  # No warning
print(np.array(0) // np.array(0))  # No warning
print(np.array([np.nan]).astype(int).astype(float))  # No warning

nan
0
[-9.22337204e+18]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [55]:
y = np.sqrt(-1) == np.emath.sqrt(-1)
print(y)

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [56]:
a = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
b = np.datetime64('today', 'D')
c = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday:", a)
print("Today:", b)
print("Tomorrow:", c)

Yesterday: 2024-12-02
Today: 2024-12-03
Tomorrow: 2024-12-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [57]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [58]:
u = np.ones(3)*1
v = np.ones(3)*2
print(np.add(u,v,out=v))
print(np.divide(u,2,out=u))
print(np.negative(u,out=u))
print(np.multiply(u,v,out=u))
print(u)
print(v)

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]
[-1.5 -1.5 -1.5]
[3. 3. 3.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [59]:
x = np.random.uniform(0,10,10)
print(x - x%1)
print(x // 1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))

[0. 5. 7. 8. 3. 0. 4. 3. 8. 4.]
[0. 5. 7. 8. 3. 0. 4. 3. 8. 4.]
[0. 5. 7. 8. 3. 0. 4. 3. 8. 4.]
[0 5 7 8 3 0 4 3 8 4]
[0. 5. 7. 8. 3. 0. 4. 3. 8. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [60]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [61]:
a = np.random.randint(0,10,10)
print(a)

[5 3 9 0 2 2 0 5 7 7]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [62]:
a = np.linspace(0,1,12,endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [63]:
c = np.random.random(10)
c.sort()
print(c)

[0.225185   0.22599144 0.24833293 0.37410922 0.40257177 0.4159843
 0.54202321 0.57477033 0.7660051  0.78621636]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [66]:
a = np.arange(10)
np.add.reduce(a)


45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [67]:
b =  np.random.randint(0,2,5)
c = np.random.randint(0,2,5)
print(np.allclose(b,c))
print(np.array_equal(b,c))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [72]:
import numpy as np

y = np.zeros(10)  # Create an array
y.flags.writeable = False  # Make the array read-only
print("Array y:", y)  # This works fine
# y[0] = 1  # Uncommenting this line will raise a ValueError
y.flags.writeable = True
y[0] = 1
print("Modified Array y:", y)


Array y: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Modified Array y: [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [73]:
x = np.random.random((10,2))
y,z = x[:,0], x[:,1]
r = np.sqrt(y**2+z**2)
t = np.arctan2(z,y)
print(r)
print(t)

[0.46159803 1.17778193 0.77708237 1.25848176 0.56681559 0.69427478
 1.18340118 0.15368828 0.36562364 0.9573146 ]
[1.29528539 0.58542723 0.30038453 0.7894281  0.37045613 0.50936747
 0.60512759 0.3153806  1.29259447 0.28272239]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [74]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.5805912  0.83451224 0.         0.73447174 0.84871983 0.75549455
 0.12375988 0.62683224 0.43958984 0.57974803]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [75]:
c = np.zeros((5,5), [('x',float),('y',float)])
c['x'], c['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(c)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [76]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x, y)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [78]:
n = [np.int8, np.int32, np.int64]
print(np.iinfo(n[0]))
print(np.iinfo(n[1]))
print(np.iinfo(n[2]))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



#### 49. How to print all the values of an array? (★★☆)

In [79]:
x = np.zeros((4,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [80]:
y = np.arange(100)
z = np.random.uniform(0,100)
index = (np.abs(y-z)).argmin()
print(y[index])

40


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)